version: 2

defaults: &defaults
  working_directory: ~/styleguide-components
  docker:
    - image: circleci/node:lts-browsers

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_READ" >> ~/.npmrc
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Lint checks
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/styleguide-components
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - run:
          name: Config github
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "tw-circleci"
      - run:
          name: Deploy changes
          command: |
            npm run copy-files-to-dist
            npm run build
            npm run deploy-for-branch
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/styleguide-components
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - run:
          name: Config github
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "tw-circleci"
      - run:
          name: Release latest version to production
          command: |
            npm run copy-files-to-dist
            npm run build
            npm run deploy
            npm run release-to-github
            npm publish dist/ --access=public
            npm run deploy:demo
  beta-release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/styleguide-components
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - run:
          name: Config github
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "circleci@transferwise.com"
            git config --global user.name "tw-circleci"
      - run:
          name: Release beta version
          command: |
            npm run copy-files-to-dist
            npm run build
            npm run deploy
            npm run release-to-github
            npm publish dist/ --access=public --tag beta
            npm run deploy:demo

workflows:
  version: 2
  build_and_publish:
    jobs:
      - test:
          context: frontend-build
          filters:
            branches:
              ignore:
                - gh-pages
                - releases
      - deploy:
          context: frontend-build
          requires:
            - test
          filters:
            branches:
              ignore:
                - gh-pages
                - master
      - release:
          context: frontend-publish
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - beta-release:
          context: frontend-publish
          requires:
            - test
          filters:
            branches:
              only:
                - beta
